server:
  port: 8083

spring:
  application:
    name: CLAIM-FRAUD-AI-SERVICE
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/fraud_claim_db
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ai-fraud-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.fraudclaimdetector.fraud_ai_service.event.ClaimSubmittedEvent

kafka:
  topic:
    name: contract-uploaded

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}
    model: gemini-1.5-flash

logging:
  level:
    com.fraudclaimdetector: DEBUG
    org.springframework.web: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true